mode: train
data:
  train_paths: ['data/libri_train/data_list_sorted.json']
  dev_paths: ['data/libri_dev/data_list_sorted.json']
  text:
    mode: character
    vocab: data/libri_train/vocab_char.txt

model:
  name: ctc_asr
  extractor:
    name: fbank
    train: false
    feature: hidden_states
  encoder:
    hid_dim: 256
    n_layers: 2
    module: LSTM
    bidirectional: true
    dropout: 0.2
  optim:
    algo: Adam
    kwargs:
      lr: 0.0001
  specaugment:
    freq_mask_range: [0, 20]
    freq_mask_num: 2
    time_mask_range: [0, 40]
    time_mask_num: 2
    time_mask_max: 1.0
    time_warp_w: 40

hparam:
  train_batch_size: 16
  val_batch_size: 16
  accum_grad: 1
  grad_clip: 5
  njobs: 4
  pin_memory: true

checkpoint_callbacks:
  monitor: val_wer
  mode: min
  save_top_k: 5  # -1: all ckpts will be saved

trainer:
  max_epochs: 50
  max_steps: 50000
  gpus: 1
  precision: 16
  logger: true
  default_root_dir: model/ctc_libri-1h_char
  deterministic: true
